website="https://pasgal-bs.cs.ucr.edu/bin/"
graphs = [
"Epinions1",
"Slashdot",
"DBLP",
"com-youtube",
"skitter",
"in_2004",
"soc-LiveJournal1",
"hollywood_2009",
"socfb-uci-uni",
"socfb-konect",
"com-orkut",
"indochina",
"eu-2015-host",
"uk-2002",
"arabic",
"twitter",
"friendster",
"sd_arc"
]